export const categories = [
  {
    name: "Men's",
    link: "/shop?gender=men",
    sections: [
      {
        title: "Shoes",
        items: [
          { name: "Road Running", link: "/shop?gender=men&category=road-running" },
          { name: "Light Trail", link: "/shop?gender=men&category=light-trail" },
          { name: "Fell Running & Technical Trail", link: "/shop?gender=men&category=fell-running" },
          { name: "Track & Field", link: "/shop?gender=men&category=track-field" },
          { name: "Race Day", link: "/shop?gender=men&category=race-day" },
          { name: "All Running Shoes", link: "/shop?gender=men&category=shoes" },
          { name: "Hiking", link: "/shop?gender=men&category=hiking" },
          { name: "Gym", link: "/shop?gender=men&category=gym" },
          { name: "Court", link: "/shop?gender=men&category=court" },
          { name: "Sandals", link: "/shop?gender=men&category=sandals" },
          { name: "View All Shoes", link: "/shop?gender=men&category=shoes" },
        ],
      },
    
      {
        title: "Sports & Top Brands",
        items: [
          { name: "Running", link: "/shop?gender=men&category=sports-running" },
          { name: "Hiking", link: "/shop?gender=men&category=sports-hiking" },
          { name: "Biking", link: "/shop?gender=men&category=sports-biking" },
          { name: "Climbing", link: "/shop?gender=men&category=sports-climbing" },
          { name: "Gym", link: "/shop?gender=men&category=sports-gym" },
          { name: "Hockey", link: "/shop?gender=men&category=sports-hockey" },
          { name: "Padel", link: "/shop?gender=men&category=sports-padel" },
          { name: "Swimming", link: "/shop?gender=men&category=sports-swimming" },
          { name: "Squash", link: "/shop?gender=men&category=sports-squash" },
          { name: "Tennis", link: "/shop?gender=men&category=sports-tennis" },
          { name: "Triathlon", link: "/shop?gender=men&category=sports-triathlon" },
          { name: "Top Brands: adidas, ASICS, HOKA, Nike, Salomon, Under Armour", link: "/shop?gender=men&category=brands" },
        ],
      },
    ],
  },
  {
    name: "Women's",
    link: "/shop?gender=women",
    sections: [
      {
        title: "Shoes",
        items: [
          { name: "Road Running", link: "/shop?gender=women&category=road-running" },
          { name: "Light Trail", link: "/shop?gender=women&category=light-trail" },
          { name: "Fell Running & Technical Trail", link: "/shop?gender=women&category=fell-running" },
          { name: "Track & Field", link: "/shop?gender=women&category=track-field" },
          { name: "Race Day", link: "/shop?gender=women&category=race-day" },
          { name: "All Running Shoes", link: "/shop?gender=women&category=shoes" },
          { name: "Hiking", link: "/shop?gender=women&category=hiking" },
          { name: "Gym", link: "/shop?gender=women&category=gym" },
          { name: "Court", link: "/shop?gender=women&category=court" },
          { name: "Sandals", link: "/shop?gender=women&category=sandals" },
          { name: "View All Shoes", link: "/shop?gender=women&category=shoes" },
        ],
      },
      {
        title: "Accessories",
        items: [
          { name: "Backpacks", link: "/shop?gender=women&category=backpacks" },
          { name: "Gloves", link: "/shop?gender=women&category=gloves" },
          { name: "GPS & Watches", link: "/shop?gender=women&category=gps-watches" },
          { name: "Headwear", link: "/shop?gender=women&category=headwear" },
          { name: "Hydration", link: "/shop?gender=women&category=hydration" },
          { name: "Injury Accessories", link: "/shop?gender=women&category=injury-accessories" },
          { name: "Nutrition", link: "/shop?gender=women&category=nutrition" },
          { name: "Socks", link: "/shop?gender=women&category=socks" },
          { name: "View All Accessories", link: "/shop?gender=women&category=accessories" },
        ],
      },
      {
        title: "Sports & Top Brands",
        items: [
          { name: "Running", link: "/shop?gender=women&category=sports-running" },
          { name: "Hiking", link: "/shop?gender=women&category=sports-hiking" },
          { name: "Biking", link: "/shop?gender=women&category=sports-biking" },
          { name: "Climbing", link: "/shop?gender=women&category=sports-climbing" },
          { name: "Gym", link: "/shop?gender=women&category=sports-gym" },
          { name: "Hockey", link: "/shop?gender=women&category=sports-hockey" },
          { name: "Netball", link: "/shop?gender=women&category=sports-netball" },
          { name: "Padel", link: "/shop?gender=women&category=sports-padel" },
          { name: "Tennis", link: "/shop?gender=women&category=sports-tennis" },
          { name: "Triathlon", link: "/shop?gender=women&category=sports-triathlon" },
          { name: "Swimming", link: "/shop?gender=women&category=sports-swimming" },
          { name: "Yoga", link: "/shop?gender=women&category=sports-yoga" },
          { name: "Top Brands: adidas, ASICS, HOKA, Nike, Salomon, Under Armour", link: "/shop?gender=women&category=brands" },
        ],
      },
    ],
  },
  {
    name: "Kids'",
    link: "/shop?gender=kids",
    sections: [
      {
        title: "By Product",
        items: [
          { name: "Kids Shoes", link: "/shop?gender=kids&category=kids-shoes" },
          { name: "Kids Running Shoes", link: "/shop?gender=kids&category=kids-running" },
          { name: "Accessories", link: "/shop?gender=kids&category=accessories" },
          { name: "Bottoms", link: "/shop?gender=kids&category=bottoms" },
          { name: "Compression", link: "/shop?gender=kids&category=compression" },
          { name: "Jackets", link: "/shop?gender=kids&category=jackets" },
          { name: "Long Sleeve Tops", link: "/shop?gender=kids&category=long-sleeve-tops" },
          { name: "Sandals", link: "/shop?gender=kids&category=sandals" },
          { name: "Shorts", link: "/shop?gender=kids&category=shorts" },
          { name: "View All Products", link: "/shop?gender=kids&category=products" },
        ],
      },
      {
        title: "Sports",
        items: [
          { name: "Running", link: "/shop?gender=kids&category=sports-running" },
          { name: "Hiking", link: "/shop?gender=kids&category=sports-hiking" },
          { name: "Badminton", link: "/shop?gender=kids&category=sports-badminton" },
          { name: "Cricket", link: "/shop?gender=kids&category=sports-cricket" },
          { name: "Gym", link: "/shop?gender=kids&category=sports-gym" },
          { name: "Handball", link: "/shop?gender=kids&category=sports-handball" },
          { name: "Hockey", link: "/shop?gender=kids&category=sports-hockey" },
          { name: "Tennis", link: "/shop?gender=kids&category=sports-tennis" },
          { name: "Triathlon", link: "/shop?gender=kids&category=sports-triathlon" },
          { name: "Squash", link: "/shop?gender=kids&category=sports-squash" },
          { name: "View All Sports", link: "/shop?gender=kids&category=sports" },
        ],
      },
      {
        title: "Top Brands",
        items: [
          { name: "adidas", link: "/shop?gender=kids&category=adidas" },
          { name: "ASICS", link: "/shop?gender=kids&category=asics" },
          { name: "Keen", link: "/shop?gender=kids&category=keen" },
          { name: "Merrell", link: "/shop?gender=kids&category=merrell" },
          { name: "Mizuno", link: "/shop?gender=kids&category=mizuno" },
          { name: "Regatta", link: "/shop?gender=kids&category=regatta" },
          { name: "Salomon", link: "/shop?gender=kids&category=salomon" },
          { name: "Saucony", link: "/shop?gender=kids&category=saucony" },
          { name: "Skechers", link: "/shop?gender=kids&category=skechers" },
          { name: "Under Armour", link: "/shop?gender=kids&category=under-armour" },
          { name: "View All Top Brands", link: "/shop?gender=kids&category=brands" },
        ],
      },
    ],
  },
];
